### ISSUE TITLE
Add Support for FramedBlocks

### ISSUE THREAD

**Issue by TobsenD** [TobsenD/XTones-Reworked#5]
As requested we should also support Framed Blocks.
See comment in #4 

https://github.com/XFactHD/FramedBlocks/issues/299

**Comment by XFactHD** [comment]
FramedBlocks dev here, the request on #4 to make the XTones blocks have a BlockEntity to be compatible with FramedBlocks is a misunderstanding. The reason the Glaxx block specifically does not work is that it's a non-solid block (like vanilla glass) and those blocks don't allow me to programmatically make sure they are actually full cubes. For that reason, these blocks must be tagged with the `framedblocks:frameable` block tag. This tag already includes a few important vanilla and Forge tags, including `forge:glass`, but since Glaxx is not tagged as glass it is not picked up by default. The fix would be to either tag Glaxx as `forge:glass` if it makes sense to categorize it as such or otherwise tag it as `framedblocks:frameable` directly.

**Comment by TobsenD** [comment]
Thanks for the info. This is exactly what i had taken from your comment in the ticket on your side and also wanted to try first.
